name: Build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # Temporarily removing constellations
        namespace: [ avalon, marble_tracks, minecraft, traffic_lights ]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@main
      - name: Setup JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Setup files
        run: ./gradlew setupFiles
      - name: Build models
        run: ./gradlew build -Pnamespace="${{ matrix.namespace }}"
      - name: Capture build artifacts
        uses: actions/upload-artifact@main
        with:
          name: Models ${{ matrix.namespace }}
          path: build/models/${{ matrix.namespace }}/
